/* User Action Types */
export const GET_USER = "USER/GET_USER";
export const USER_STATUS = "USER/USER_STATUS";
export const GET_USERS = "USER/GET_USERS";
export const USERS_STATUS = "USER/USERS_STATUS";

/* Notification Action Types*/
export const SET_CURRENT_NOTIFS_PV = "NOTIFICATIONS/SET_CURRENT_NOTIFS_PV";
export const SET_CURRENT_NOTIFS_PB = "NOTIFICATIONS/SET_CURRENT_NOTIFS_PB";

/* Channel Action Types */
export const GET_CHANNELS = "CHANNELS/GET_CHANNELS";
export const CHANNELS_STATUS = "CHANNELS/CHANNELS_STATUS";
export const SET_CURRENT_CHANNEL = "CHANNELS/SET_CURRENT_CHANNEL";
export const SET_PRIVATE_CHANNEL = "CHANNELS/SET_PRIVATE_CHANNEL";
export const SET_USER_POSTS = "CHANNELS/SET_USER_POSTS";

/* Typing Action Types */
export const GET_TYPING = "TYPING/GET_TYPING";
export const TYPING_STATUS = "TYPING/TYPING_STATUS";

/* Messages Action Types */
export const GET_MESSAGES = "MESSAGES/GET_MESSAGES";
export const MESSAGES_STATUS = "MESSAGES/MESSAGES_STATUS";
export const GET_PRIVATE_MESSAGES = "MESSAGES/GET_PRIVATE_MESSAGES";
export const PRIVATE_MESSAGES_STATUS = "MESSAGES/PRIVATE_MESSAGES_STATUS";

/* Params Action Types */
export const SET_PARAMS = "PARAMS/SET_PARAMS";
export const ACTIVE_COLOR = "PARAMS/ACTIVE_COLOR";
export const SET_LANG = "PARAMS/SET_LANG";

/* Presences Action Types */
export const GET_PRESENCES = "PRESENCES/GET_PRESENCES";
export const PRESENCES_STATUS = "PRESENCES/PRESENCES_STATUS";
export const GET_CONNECTED = "PRESENCES/GET_CONNECTED";
export const CONNECTED_STATUS = "PRESENCES/CONNECTED_STATUS";

/* Notes Types */
export const GET_NOTES = "NOTES/GET_NOTES";
export const NOTES_STATUS = "NOTES/NOTES_STATUS";

/* Settings Types */
export const GET_SETTINGS = "SETTINGS/GET_SETTINGS";
export const SETTINGS_STATUS = "SETTINGS/SETTINGS_STATUS";

/* Patients Types */
export const GET_PATIENTS = "PATIENTS/GET_PATIENTS";
export const PATIENTS_STATUS = "PATIENTS/PATIENTS_STATUS";
